zuul:
  # 全部服务忽略敏感头（全部服务都可以传递cookie）
  sensitive-headers: 
  routes:
  # /myProduct/product/list -> /product/product/list
    myProduct:
      path: /myProduct/**
      serviceid: product
      # 敏感头过滤
      sensitiveHeaders:
  # 简洁写法
#    product: /myProduct/**
  # 排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
management:
  security:
    enabled: false
spring:
  redis:
    host: 47.93.24.255
    port: 6379    
